name = "flexichat"
compatibility_date = "2025-09-30"

[assets]
not_found_handling = "single-page-application"
directory = "./dist"

[[routes]]
pattern = "flexichat.tools.slowfademan.com"
custom_domain = true

